blog/urls.py
# # blog/urls.py
# from django.conf.urls import url


# from .views import post_list, post_detail

# urlpatterns = [

#     url(r'^$',
# 	        post_list,
# 	        name='blog_post_list'),

#     url(r'^(?P<year>\d{4})/'
# 	        r'(?P<month>\d{1,2})/'
# 	        r'(?P<slug>[\w\-]+)/$',
# 	        post_detail,
# 	        name='blog_post_detail'),
# ]


# USING CLASS-BASED VIEW
# blog/urls.py
from django.conf.urls import url


from .views import PostList, post_detail

urlpatterns = [

    url(r'^$',
	        # post_list,
	        PostList.as_view(template_name = 'blog/post_list.html'),
	        name='blog_post_list'),

    url(r'^(?P<year>\d{4})/'
	        r'(?P<month>\d{1,2})/'
	        r'(?P<slug>[\w\-]+)/$',
	        post_detail,
	        name='blog_post_detail'),
]

organizer/urls.py
# organizer/urls.py
from django.conf.urls import url


from .views import (
    startup_detail, startup_list, 
    tag_detail, tag_list)


urlpatterns = [
    url(r'^startup/$',
	        startup_list,
	        name='organizer_startup_list'),

	url(r'^startup/(?P<slug>[\w\-]+)/$',
			startup_detail,
			name='organizer_startup_detail'),

    url(r'^tag/$',
	        tag_list,
	        name='organizer_tag_list'),

    url(r'^tag/(?P<slug>[\w\-]+)/$',
	        tag_detail,
	        name='organizer_tag_detail'),
]

suorganizer/urls.py
# from django.contrib import admin
# from django.urls import path
# from django.conf.urls import include, url

# from organizer import urls as organizer_urls
# from blog import urls as blog_urls

# urlpatterns = [

# 	# ADMIN
#     path('admin/', admin.site.urls),

#     # ORGANIZER
#     url(r'^', include(organizer_urls)),

#     # BLOG
#     url(r'^blog/', include(blog_urls)),
# ]


# USING CLASS-BASED VIEW
from django.contrib import admin
from django.urls import path
from django.conf.urls import include, url

from organizer import urls as organizer_urls
from blog import urls as blog_urls
from blog.views import PostList
from suorganizer.views import redirect_root

urlpatterns = [

    # BLOG
    # '''This url redirect to: http://127.0.0.1:8000/blog/'''
    url(r'^$', redirect_root),
    # '''This url returns: http://127.0.0.1:8000/blog/'''
    url(r'^$', PostList.as_view()), # replace by url above (line 50)
    url(r'^blog/', include(blog_urls)), 

    # ORGANIZER
    url(r'^', include(organizer_urls)),

	# ADMIN
    path('admin/', admin.site.urls),

]

blog/models.py
# blog/models.py
from django.db import models
from django.urls import reverse

from organizer.models import Startup, Tag

# Create your models here.

# BLOG MODELS: Post
class Post(models.Model):

	title 	= models.CharField(
			max_length=63)
	slug 	= models.SlugField(
			max_length=63,
			help_text='A label for URL config',
			unique_for_month='pub_date')
	text 	= models.TextField()
	pub_date= models.DateField(
			'date published',
			auto_now_add=True)
	# ManyToMany Rel:
	## A post may have many tags
	## A tag may belongs to many posts
	tags 	= models.ManyToManyField(
			Tag,
			related_name='blog_post')
	# ManyToMany Rel:
	## A startup may posting many posts
	## A post may belongs to many startup
	startups= models.ManyToManyField(
			Startup,
			related_name='blog_post')


	class Meta:
		verbose_name  = 'blog post'
		ordering 	  = ['-pub_date', 'title']
		get_latest_by = 'pub_date'


	def __str__(self):
		return "{} on {}".format(
			self.title,
			self.pub_date.strftime('%Y-%m-%d'))


	def get_absolute_url(self):
		return reverse(
			'blog_post_detail',
			kwargs={'year': self.pub_date.year,
					'month': self.pub_date.month,
					'slug': self.slug})

organizer/models.py
# organizer/models.py
from django.db import models
from django.urls import reverse

# Create your models here.

# ORGANIZER MODELS: Tag
class Tag(models.Model):

	name = models.CharField(
			max_length=31, unique=True)
	slug = models.SlugField(
			unique=True,
			help_text='A label for URL config.')


	def __str__(self):
		return self.name 


	def get_absolute_url(self):
		return reverse('organizer_tag_detail',
			kwargs={'slug': self.slug})
			# args=(self.slug,)) # It is also possible to use args instead of kwargs


# ORGANIZER MODELS: Startup
class Startup(models.Model):

	name = models.CharField(
			max_length=31,
			db_index=True)
	slug = models.SlugField(
			max_length=31,
			unique=True,
			help_text='A label for URL config.')
	description = models.TextField()
	founded_date = models.DateField(
			'date founded')
	contact = models.EmailField(
			max_length=225)
	website = models.URLField()
	# ManyToMany Rel: 
	## A Startup may have many tags
	## A tag may belongs to many startup
	tags = models.ManyToManyField(Tag)


	class Meta:
		ordering 	  = ['name']
		get_latest_by = 'founded_date'


	def __str__(self):
		return self.name 
		

	def get_absolute_url(self):
		return reverse('organizer_startup_detail',
			kwargs={'slug': self.slug})



# ORGANIZER MODELS: NewsLink
class NewsLink(models.Model):

	title = models.CharField(
			max_length=63)
	pub_date = models.DateField(
			'date published')
	link = models.URLField(
			max_length=225)
	# OneToMany Rel: 
	## A startup may have many newslink
	startup = models.ForeignKey(
			Startup,
			on_delete=models.CASCADE)


	class Meta:
		verbose_name  = 'news article'
		ordering 	  = ['-pub_date']
		get_latest_by = 'pub_date'


	def __str__(self):
		return "{}:{}".format(
			self.startup, self.title)

blog/views.py
# # blog/views.py
# from django.shortcuts import render, get_object_or_404

# # Create your views here.

# from .models import Post


# # Post List
# # http://127.0.0.1:8000/blog/
# def post_list(request):
# 	post_list = Post.objects.all()
# 	context = {
# 		'post_list':post_list
# 	}
# 	return render(request, 'blog/post_list.html',context)


# # Post Detail: 
# # http://127.0.0.1:8000/blog/2021/05/flask-essentials/
# def post_detail(request, year, month, slug):
# 	post = get_object_or_404(
# 			Post,
# 			pub_date__year=year,
# 			pub_date__month=month,
# 			slug=slug)
# 	context = {
# 		'post':post
# 	}
# 	return render(request, 'blog/post_detail.html',context)  


# USING CLASS-BASED VIEWS

# blog/views.py
from django.shortcuts import render, get_object_or_404
from django.views.generic import View
from django.views.decorators.http import require_http_methods

# Create your views here.

from .models import Post


# Post List
# http://127.0.0.1:8000/blog/
class PostList(View):

	template_name = 'blog/post_list.html'

	def get(self, request):
		post_list = Post.objects.all()
		context = {
			'post_list':post_list
		}

		return render(request, self.template_name, context)


# Post Detail: 
# http://127.0.0.1:8000/blog/2021/05/flask-essentials/
@require_http_methods(['HEAD', 'GET'])
def post_detail(request, year, month, slug):
	post = get_object_or_404(
			Post,
			pub_date__year=year,
			pub_date__month=month,
			slug=slug)
	context = {
		'post':post
	}
	return render(request, 'blog/post_detail.html',context)  

organizer/views.py
from django.shortcuts import render, get_object_or_404
from .models import Startup, Tag

# Create your views here.

# Startup List
def startup_list(request):
	startup_list = Startup.objects.all()
	context = {
		'startup_list': startup_list
	}
	return render(request,'organizer/startup_list.html', context)


# Startup Detail
def startup_detail(request, slug):
	startup = get_object_or_404(Startup, slug__iexact=slug)
	context = {
		'startup': startup
	}
	return render(request,'organizer/startup_detail.html', context)



# Tag detail page
def tag_detail(request, slug):
	# slug = ?
	tag = get_object_or_404(Tag, slug__iexact=slug)
	context = {
		'tag': tag
	}
	return render(request, 'organizer/tag_detail.html', context)


# Homepage (tag_list) view
def homepage(request):
	tag_list = Tag.objects.all()
	context = {
		'tag_list': tag_list
	}
	return render(request, 'organizer/tag_list.html', context)






def tag_detail(request, slug):
    tag = get_object_or_404(
        Tag, slug__iexact=slug)
    return render(
        request,
        'organizer/tag_detail.html',
        {'tag': tag})
def tag_list(request):
    return render(
        request,
        'organizer/tag_list.html',
        {'tag_list': Tag.objects.all()})

suorganizer/views.py
# suorganizer/views.py
from django.shortcuts import redirect

def redirect_root(request):
	return redirect('blog_post_list')

blog/templates/blog/post_detail.html
{# organizer/templates/blog/post_detail.html #}
{% extends "base.html" %}

{% block title %}
	Post Detail
{% endblock %}

{% block content %}
<article>

    <header>
      <h2>{{ post.title|title }}</h2>
      <p>
        Written on
        <time datetime="{{ post.pub_date|date:"Y-m-d" }}">
          {{ post.pub_date|date:"l, F j, Y" }}
        </time>
      </p>
    </header>

    {{ post.text|linebreaks }}

  {% if post.startups.all or post.tags.all %}
    <footer>

      {% if post.startups.all %}
          <section>
            <h3>Startup{{ post.startups.count|pluralize }}</h3>
            <ul>
              {% for startup in post.startups.all %}
                <li><a href="{{ startup.get_absolute_url }}">
                  {{ startup.name }}
                </a></li>
              {% endfor %}
            </ul>
          </section>
      {% endif %}

      {% if post.tags.all %}
          <section>
            <h3>Tag{{ post.tags.count|pluralize }}</h3>
            <ul>
              {% for tag in post.tags.all %}
                <li><a href="{{ tag.get_absolute_url }}">
                  {{ tag.name|title }}
                </a></li>
              {% endfor %}
            </ul>
          </section>
      {% endif %}

    </footer>
  {% endif %}

</article>
{% endblock %}

blog/templates/blog/post_list.html
{# organizer/templates/blog/post_list.html #}
{% extends "base.html" %}

{% block title %}
	Post List
{% endblock %}

{% block content %}
    {% for post in post_list %}
      <article>
        <header>
          <h2>
            {# http://127.0.0.1:8000/blog/2021/5/flask-essentials/ #}
            {# <a href="{% url 'blog_post_detail' post.pub_date.year post.pub_date.month post.slug %}"> #}
            <a href="{{ post.get_absolute_url }}"> 
                {# Flask Essentials #}
                {{ post.title|title }}</a>
          </h2>
          <p>
            Written on:
            <time datetime="{{ post.pub_date|date:"Y-m-d" }}">
              {{ post.pub_date|date:"l, F j, Y" }}
            </time>
          </p>
        </header>
        <p>{{ post.text|truncatewords:20 }}</p>
        <p>
          <a href="">
            Read more&hellip;</a>
        </p>
      </article>
    {% empty %}
      <p><em>No Blog Posts Available</em></p>
    {% endfor %}
{% endblock %}

organizer/templates/organizer/startup_detail.html
{# organizer/templates/organizer/startup_detail.html #}
{% extends "base.html" %}

{% block title %}
	Startups Detail
{% endblock %}

{% block content %}
<article>

  <h2>{{ startup.name }}</h2>
  <dl>
    <dt>Date Founded</dt>
      <dd>{{ startup.founded_date }}</dd>
    <dt>Website</dt>
      <dd>{{ startup.website }}</dd>
    <dt>Contact</dt>
      <dd>{{ startup.contact }}</dd>

      <dt>Tag{{ startup.tags.count|pluralize }}</dt>
        {% for tag in startup.tags.all %}
          <dd><a href="{{ tag.get_absolute_url }}">
            {{ tag.name|title }}
          </a></dd>
        {% endfor %}

  </dl>

  <p>{{ startup.description }}</p>

      {% if startup.newslink_set.all %}
          <section>
            <h3>Recent News</h3>
            <ul>
              {% for newslink in startup.newslink_set.all %}
                <li>
                  <a href="{{ newslink.link }}">
                    {{ newslink.title|title }}</a>
                </li>
              {% endfor %}
            </ul>
          </section>
      {% endif %}

      {% if startup.blog_posts.all %}
          <section>
            <h3>Blog Post{{ startup.blog_posts.all|pluralize }}</h3>
            <ul>
              {% for post in startup.blog_posts.all %}
                <li>
                  <a href="{{ post.get_absolute_url }}">
                    {{ post.title|title }}</a>
                </li>
              {% endfor %}
            </ul>
          </section>
      {% endif %}

</article>
{% endblock %}

organizer/templates/organizer/startup_list.html
{# organizer/templates/organizer/startup_list.html #}
{% extends "base.html" %}

{% block title %}
	Startups
{% endblock %}

{% block content %}
  <h2>Startup List</h2>
  <ul>
    {% for startup in startup_list %}
      <li>
        {# http://127.0.0.1:8000/startup/django-for-beginners/ #}
        {# <a href="{% url 'organizer_startup_detail' slug=startup.slug %}"> #}
        <a href="{{ startup.get_absolute_url }}">
          {# Django for Beginners #}
          {{ startup.name }}</a>
      </li>
    {% empty %}
      <li><em>No Startups Available</em></li>
    {% endfor %}
  </ul>
{% endblock %}

organizer/templates/organizer/tag_detail.html
{# organizer/templates/organizer/tag_detail.html #}
{% extends "base.html" %}

{% block title %}
	 Tag detail
{% endblock title %}

{% block content %}
  
  <h2>{{ tag.name|title }}</h2>
  {% if tag.startup_set.all %}
    <section>
      <h3>Startup{{ tag.startup_set.count|pluralize }}</h3>
      <p>
        Tag is associated with
        {{ tag.startup_set.count }}
        startup{{ tag.startup_set.count|pluralize }}.
      </p>
      <ul>
        {% for startup in tag.startup_set.all %}
          <li><a href="{{ startup.get_absolute_url }}">
            {{ startup.name }}
          </a></li>
        {% endfor %}
      </ul>
    </section>
  {% endif %}
      {% if tag.blog_posts.all %}
        <section>
          <h3>Blog Post{{ tag.blog_posts.count|pluralize }}</h3>
          <ul>
            {% for post in tag.blog_posts.all %}
              <li><a href="{{ post.get_absolute_url }}">
                {{ post.title|title }}
              </a></li>
            {% endfor %}
          </ul>
        </section>
      {% endif %}
      {% if not tag.startup_set.all and not tag.blog_posts.all %}
        <p>This tag is not related to any content.</p>
      {% endif %}	
	
{% endblock content %}

organizer/templates/organizer/tag_list.html
{# organizer/templates/organizer/tag_list.html #}
{% extends "base.html" %}

{% block title %}
	 Tag list
{% endblock title %}

{% block content %}
	
	<h2>Tag List</h2>
	<ul>
		{% for tag in tag_list %}
		<li>
			{# http://127.0.0.1:8000/tag/django/ #}
			{# <a href="{% url 'organizer_tag_detail' tag.slug %}"> #}
			{# Above code is similar to this:<a href="/tag/{{ tag.slug }}/"> #}
			<a href="{{ tag.get_absolute_url }}">				
				{{ tag.name|title }}</a>
		</li>
		{% empty %}
			<li><em>There are currently no Tags available.</em></li>
		{% endfor %}
	</ul>

{% endblock content %}

templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
	<meta charset="utf-8">
	<title>
		{% block title %}
			{{ block.super }}
		{% endblock title %} - Startup Organizer
	</title>
	<meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
	<meta name="viewport" content="width=device-width, initial-scale=1">
	<!--[if IE]><script
	src="http://html5shiv.googlecode.com/svn/trunk/html5.js">
	</script><![endif]-->
</head>
<body>
	<div class="container">
		<header>
			<h1>Startup Organizer</h1>
		</header>
		<nav>
			<ul>
				<li>
					<a href="{% url 'blog_post_list' %}">Blog</a>
				</li>
				<li>
					<a href="{% url 'organizer_startup_list' %}">Startups</a>
				</li>
				<li>
					<a href="{% url 'organizer_tag_list' %}">Tags</a>
				</li>
			</ul>
        </nav>
		<main>
			{% block content %}
				
			{% endblock content %}
		</main>
	</div>
	<footer class="footer">
		<p>&copy; 2015
			<a href="https://AndrewsForge.com/">Andrew Pinkham</a>
		</p>
		<p>Created for 
			<a href="https://Django-Unleashed.com/">Django Unleashed</a>
		</p>
	</footer>
</body>
</html>